name: C++ Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install compiler
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build project
      run: g++ -std=c++17 main.cpp Complex.cpp -o app